Создать 2 матрицы 4х3 и сложить их
Создать 2 матрицы 4х3 и 6х4 и перемножить их

In [ ]:
import numpy as np

a = np.arange(1,13).reshape(4,3)
b = np.arange(13,25).reshape(4,3)

c = np.arange(1,13).reshape(3,4)
d = np.dot(a,c)

a = a + b


print(a,d,sep='\n')

[[14 16 18]
 [20 22 24]
 [26 28 30]
 [32 34 36]]
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]
 [173 206 239 272]]


Создать матрицу 3 на 3 и найти ее определитель

In [ ]:
a = np.random.rand(3,3)

print(np.linalg.det(a))

-0.05508081381089797


Решить систему уравнений

3х + 2у = 5

2х - 1у = 3

In [ ]:
a1 = np.array([[3., 2.],[2.,-1.]])
a2 = np.array([[5.],[3.]])

print(np.linalg.solve(a1,a2))

[[1.57142857]
 [0.14285714]]


Выкачать 1000 вакансий с https://api.hh.ru/vacancies?text=Программист&per_page=100&area=1&area=2&{}
Найти зп по удаленной работе, полному дню и гибкому графику программистов Python
использовать Numpy

In [ ]:
import requests
import numpy as np

salary = lambda x: [x['salary']['from'], x['salary']['to'], x['salary']['currency'], x['salary']['gross']] if x['salary'] is not None else [None]*4
schedule = lambda x: [x['schedule']['name']] if ['schedule'] is not None else [None]

vac = []

for i in range(10):
  url = 'https://api.hh.ru/vacancies?text=Программист&per_page=100&area=1&area=2&{}'.format(str(i))
  vac += [[x['id'], x['name']] + salary(x) + schedule(x) for x in requests.get(url).json()['items']]

In [ ]:
len(vac)

1000

In [ ]:
full = np.array([],float)
remote = np.array([],float)
flexible = np.array([],float)

for i in vac:
  if i[1] is not None and 'Python' in i[1] and i[4] is not None and 'RUR' in i[4] and i[2] is not None:
    if i[-1] == 'Полный день':
      full = np.append(full,i[2])
    elif i[-1] == 'Гибкий график':
      flexible = np.append(flexible,i[2])
    elif i[-1] == 'Удаленная работа':
      remote = np.append(remote,i[2])

print('Полная занятость',np.mean(full),'Гибкий график',np.mean(flexible),'Удаленная работа',np.mean(remote))

print(len(full))
print(len(flexible))
print(len(remote))

Полная занятость 65000.0 Гибкий график nan Удаленная работа 65000.0
20
0
20


/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
