In [ ]:
import numpy as np

In [ ]:
X = np.array([
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [1,0,0],
    [0,1,1],
    [1,1,0],
    [1,0,1],
    [1,1,1],
], dtype=float)
y = np.array([[0],[1],[0],[1],[1],[0],[1],[0]], dtype=float)


lr = 1
epochs = 2


weights1_init = np.array([
    [0.79, 0.85],
    [0.44, 0.43],
    [0.43, 0.29]
], dtype=float)
weights2_init = np.array([
    [0.22],
    [0.59]
], dtype=float)

In [ ]:
def sigmoid_activation(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    sx = sigmoid_activation(x)
    return sx * (1 - sx)

def relu_activation(x):
    return np.maximum(0, x)
def relu_derivative(x):
    return (x > 0).astype(float)

In [ ]:
def train():
    weights1 = weights1_init.copy()
    weights2 = weights2_init.copy()

    activation, activation_derivative = relu_activation, relu_derivative

    for epoch in range(1, epochs+1):
        print(f"\nЭпоха: {epoch}")

        z1 = X.dot(weights1)
        a1 = activation(z1)
        z2 = a1.dot(weights2)
        a2 = sigmoid_activation(z2)

        print("W1 до обновления:\n", weights1)
        print("W2 до обновления:\n", weights2)
        print("\nz1 (скрытый слой входы):\n", z1)
        print("a1 (скрытый слой выходы):\n", a1)
        print("\nz2 (выходной слой входы):\n", z2)
        print("a2 (выход сети):\n", a2)

        error = y - a2
        d_output = error * sigmoid_derivative(z2)
        d_hidden = d_output.dot(weights2.T) * activation_derivative(z1)

        delta_weights2 = a1.T.dot(d_output) * lr
        delta_weights1 = X.T.dot(d_hidden) * lr

        print("\nΔweights2:\n", delta_weights2)
        print("Δweights1:\n", delta_weights1)

        weights2 += delta_weights2
        weights1 += delta_weights1

        print("\nweights1 после обновления:\n", weights1)
        print("weights2 после обновления:\n", weights2)
        print(f"\nСредняя ошибка: {np.mean(np.abs(error)):.4f}")

In [ ]:
train()


Эпоха: 1
W1 до обновления:
 [[0.79 0.85]
 [0.44 0.43]
 [0.43 0.29]]
W2 до обновления:
 [[0.22]
 [0.59]]

z1 (скрытый слой входы):
 [[0.   0.  ]
 [0.43 0.29]
 [0.44 0.43]
 [0.79 0.85]
 [0.87 0.72]
 [1.23 1.28]
 [1.22 1.14]
 [1.66 1.57]]
a1 (скрытый слой выходы):
 [[0.   0.  ]
 [0.43 0.29]
 [0.44 0.43]
 [0.79 0.85]
 [0.87 0.72]
 [1.23 1.28]
 [1.22 1.14]
 [1.66 1.57]]

z2 (выходной слой входы):
 [[0.    ]
 [0.2657]
 [0.3505]
 [0.6753]
 [0.6162]
 [1.0258]
 [0.941 ]
 [1.2915]]
a2 (выход сети):
 [[0.5       ]
 [0.56603696]
 [0.58673882]
 [0.6626889 ]
 [0.64935381]
 [0.73610083]
 [0.71930161]
 [0.78440097]]

Δweights2:
 [[-0.21467919]
 [-0.2353769 ]]
Δweights1:
 [[-0.0315859  -0.08470764]
 [-0.07437707 -0.19946577]
 [ 0.02430081  0.06517036]]

weights1 после обновления:
 [[0.7584141  0.76529236]
 [0.36562293 0.23053423]
 [0.45430081 0.35517036]]
weights2 после обновления:
 [[0.00532081]
 [0.3546231 ]]

Средняя ошибка: 0.5012

Эпоха: 2
W1 до обновления:
 [[0.7584141  0.76529236]
 [0.36562293 